language: c

rvm:
  - 2.2.3

notifications:
  email: false
  slack:
    secure: hD69ZlrBGvRhr5FaglkqSgv4XPNZ6XGqsbf75/blj0U6RnYNPSfYMzfuUgcgR5I+vYJoWY5qYaAFqIgQXwExnqATr7Y+UrscLOiy7pT+/WIwIuo0TQLM0XHB50FcXksVC0xlduZIM4UlaQzMvGku5R3NTw6vnCDV9ulQzXFRzyF4yQm+e8mTnCh8lO/d5r8onPqOikTmrXM1QHDYpmP3C/EQeKuIhIUTR4hHeptv02er11z1g+JQHME4uI1GEBOSnyPDYyV/7ATPJCSKcMnVRthX82Qayl6xpu5O0iIRwPeSKykN/FvqNmona4PzcU0K/JpySHhoLhKOhPqiYV329koJuZp5RORsktbYFMfEAJx9+pKNCwWFtEghFgH5HdejEmGJ53VIDxIBG1YgJHndHichEIUZHlC86AXkD0ZUkHWGyZ3g8l64jwTKlKvxJTLux7znTKLcYT8s/czC1/tAadcuF3oQlMBCKTrttRpCwt4pDUEu9N3vaKIZIuAkEY7NsjF3QAH/t44Z4jGPGQMNE10WKeEYCqQJJYoQ73PXhdo16Xobhv6zWly7MpXgImf8KGrw/zqVmEN+SUYdp7JFesmGQyuZ0xH7wJgmxb7oQ+SPnh4mTfUrfMugnUuiyljBLFX6IBn9nO/qpD8HZno7OmF67DDV51RQS1q1NlMPWKA=

branches:
  only:
    - master

dist: trusty
sudo: required

matrix:
  include:
    - os: osx
      env:
        - LLVM_VERSION="3.9.1"
        - LLVM_CONFIG="llvm-config-3.9"
        - CC1=clang-3.9
        - CXX1=clang++-3.9
        - lto=no
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - LLVM_VERSION="3.9.1"
        - LLVM_CONFIG="llvm-config-3.9"
        - CC1=gcc-5
        - CXX1=g++-5
        - lto=no

install:
  # Based on how travis-ci works, when this is run, we are in the source
  # directory for Buffy. This means, when we go to git clone and install
  # dependencies, we need to leave that directory and then return to it when
  # done.
  # If we clone into the Buffy directory, our recursive Makefile will try to
  # build the cloned dependencies and fail
  # If we clone our dependencies into another directory using `cd` and don't
  # return to our starting directory, then our `script` step will fail because
  # its in the wrong directory.
  - export INSTALL_STARTED_AT=`pwd`
  - if [ "${TRAVIS_OS_NAME}" = "osx" ];
    then
      brew update;
      brew install gmp; brew link --overwrite gmp;
      brew install pcre2 libressl;
      brew install llvm; brew link --overwrite --force llvm;
      mkdir /tmp/llvmsym;
      ln -s `which llvm-config` /tmp/llvmsym/llvm-config-3.9;
      ln -s `which clang++` /tmp/llvmsym/clang++-3.9;
      export PATH=/tmp/llvmsym:$PATH;
    fi;
  - if [ "${TRAVIS_OS_NAME}" = "linux" ];
    then
      mkdir /tmp/dl;
      cd /tmp/dl;
      wget "http://llvm.org/releases/${LLVM_VERSION}/clang+llvm-${LLVM_VERSION}-x86_64-linux-gnu-debian8.tar.xz";
      tar -xvf clang+llvm*;
      cd clang+llvm* && sudo mkdir /tmp/llvm && sudo cp -r * /tmp/llvm/;
      sudo ln -s /tmp/llvm/bin/llvm-config /usr/local/bin/${LLVM_CONFIG};
      export PATH=/tmp/llvm/bin:$PATH;
      cd /tmp/dl;
      wget ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre2-10.21.tar.bz2;
      tar -xjvf pcre2-10.21.tar.bz2;
      cd pcre2-10.21 && ./configure --prefix=/usr && make && sudo make install;
    fi;
  - echo "Installing sendence/ponyc";
    cd /tmp;
    git clone git@github.com:Sendence/ponyc.git;
    cd ponyc;
    make CC=$CC1 CXX=$CXX1;
    sudo make install;
  - echo "Installing pony-stable";
    cd /tmp;
    git clone https://github.com/jemc/pony-stable.git;
    cd pony-stable;
    sudo make install;
  - cd $INSTALL_STARTED_AT

script:
  - cd lib/wallaroo;
    stable env ponyc;
    ./wallaroo;
    cd -;
  - cd lib/sendence/;
    stable env ponyc;
    ./sendence;
    cd -;
